name: atom
version: 1.22.1
summary: A hackable text editor for the 21st Century.
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.

grade: stable
confinement: classic

parts:
  atom:
    plugin: dump
    source: https://github.com/atom/atom/releases/download/v1.22.1/atom-amd64.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=atom|Icon=/usr/share/pixmaps/atom\.png|g' usr/share/applications/atom.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gvfs-bin
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  electron-launch:
    plugin: dump
    source: files/

apps:
  atom:
    command: bin/electron-launch classic ${SNAP}/usr/share/atom/atom
    desktop: usr/share/applications/atom.desktop
  apm:
    command: usr/bin/apm
